Module message: Setting OPENBLAS_NUM_THREADS to 1. Done. 
rm: cannot remove ‘data/Tidy_Topics/*’: No such file or directory
rm: cannot remove ‘data/Tree_Distance/*’: No such file or directory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 18, in <module>
    sub = sub_info.query("sub_id == @sub_id")['sub'].iloc[0]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 3085 is out of bounds for axis 0 with size 3085
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 2931 is out of bounds for axis 0 with size 2931
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 543 is out of bounds for axis 0 with size 543
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 814 is out of bounds for axis 0 with size 814
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 4126 is out of bounds for axis 0 with size 4126
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 2340 is out of bounds for axis 0 with size 2340
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 8000 is out of bounds for axis 0 with size 8000
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 3386 is out of bounds for axis 0 with size 3386
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_hSBM.py", line 54, in <module>
    sample_ind = np.random.permutation(len(data))[range(round(10000))]
IndexError: index 7062 is out of bounds for axis 0 with size 7062
seq: invalid floating point argument: n_sub%5
Try 'seq --help' for more information.
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self._open_handles(src, kwds)
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Topic_distance_different_corpora/Python/phoenix_tree_dist.py", line 17, in <module>
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    sub_info = pd.read_csv("data/Subs.info/sub_id.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Subs.info/sub_id.csv'
